### ISSUE TITLE
Удалить рецепты светопыли и пороха из крафт стола

### ISSUE THREAD

**Issue by Spartak1997** [GT-IMPACT/GT5.09OFFBEAT#19]
IC2 добавляет ручные рецепты для светопыли и пороха, это в свою очередь ломает баланс сборки.

Необходимо удалить их!

**Comment by Pilad** [comment]
Или сюда вписать маинкрафт глоустоун
![изображение](https://user-images.githubusercontent.com/9840821/226160850-d785b8b7-8e70-4d80-ad10-090884c83e39.png)

**Comment by Pilad** [comment]
Вроде вот это отвечает за эти рецепты. но вроде только скроет их. Не факт что отключит. Нужно в тру и проверить
![изображение](https://user-images.githubusercontent.com/9840821/226160893-c50fbf48-7eae-49d1-a187-821018e53bc3.png)

**Comment by Pilad** [comment]
Было: 
![изображение](https://user-images.githubusercontent.com/9840821/226160964-d4d1ed54-bc85-4963-8b5c-282d6f9410ee.png)
Стало после disable = minecraft:glowstone_dust : 
![изображение](https://user-images.githubusercontent.com/9840821/226161895-777e2d13-8704-4730-bc2c-6ad5b22bfb18.png)

**Comment by Pilad** [comment]
Хайд реально только скрывает, но рецепт не отключает.
