### ISSUE TITLE
Перепутан режим по умолчанию у кавера.

### ISSUE THREAD

**Issue by Pilad** [GT-IMPACT/GT5.09OFFBEAT#6]
https://github.com/GT-IMPACT/GT5.09OFFBEAT/blob/fbf2b10d2d6e02b66de15caaeb89da655b0fa5cb/src/main/java/gregtech/common/covers/GT_Cover_LiquidMeter.java#L51

Изначально было инвертирован-нормал.
То есть без жидкости он выдавал 0.
Сейчас по умолчанию сразу инвертирован,как прилепишь.

**Comment by RaitGamerGR** [comment]
Кавер таким был всегда, что-то менять-путать народ, сломает многие уже готовые схемы. Изменение логичное, но лишнее

**Comment by Pilad** [comment]
> Кавер таким был всегда, что-то менять-путать народ, сломает многие уже готовые схемы. Изменение логичное, но лишнее

Нет, до введения гуи был обратный режим. Но насчёт путать народ,то возможно.

**Comment by RaitGamerGR** [comment]
Всегда было именно так, но основной аргумент это поломка ВСЕХ схем с ними
